# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "gradle"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "python"
    schedule:
      interval: "daily"
