name: Dependabot auto approve
on: push

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  actor:
    runs-on: ubuntu-latest
    steps:
      - name: Get actor
        run: echo "${{ github.actor }}"

  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: "${{ secrets.TEST_JOES_BOT }}"
